services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: drzavno
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    env_file: ./apps/api/.env
    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/drzavno
    ports:
      - "${API_PORT}:4000"
    depends_on:
      - db
      - redis

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    env_file: ./apps/web/.env.local
    ports:
      - "${WEB_PORT}:3000"
    depends_on:
      - api
